### ISSUE TITLE
include all built-in context menu items

### ISSUE THREAD

**Issue by dimitropoulos** [ceolter/ag-grid-docs#67]
The docs at https://www.ag-grid.com/javascript-grid-context-menu/ are missing most of the available defaults.  This is a really handy feature, users should know about it!

the list I pulled from menuItemMapper.ts is:

```
autoSizeAll
autoSizeThis
clearPinned
contractAll
copy
copyWithHeaders
expandAll
paste
pinLeft
pinRight
pinSubMenu
resetColumns
rowGroup
rowUnGroup
separator
toolPanel
toolPanel
valueAggSubMenu
```

**Comment by ceolter** [comment]
not all of these will work, as they need a column to work on. however i've updated docs to include the ones that are relevant (website will be updated on next release).
